#!/usr/bin/env bash
while (( "$#" )); do shift; done

TUNDERLINE=$(tput sgr 0 1)
TRED=$(tput setaf 1)
TGREEN=$(tput setaf 2)
TYELLOW=$(tput setaf 3)
TBLUE=$(tput setaf 4)
TRESET=$(tput sgr0)
TCHECKMARK="\xe2\x9c\x93"
TXMARK="\xe2\x9c\x95"
TLINE="\xe2\x8e\xaf"
TOTAL_COUNT=0
PASS_COUNT=0
FAIL_COUNT=0
PATH_BKUP="$PATH"

clear
printf "\n${TUNDERLINE}${TBLUE}Running specs...${TRESET}\n" 

bunt_error() {
    local callstack=$(caller)
    local callstack_lineno=$(echo "$callstack" | awk '{print $1}')
    local callstack_file=$(echo "$callstack" | awk '{print $2}')
    local message="$1"
    local code="${2:-1}"

    printf "\n${TRED}Error on line ${callstack_lineno} of ${callstack_file}\n"
    if [[ -n "$message" ]] ; then
        printf "${TRED}Message: ${message}; exiting with status ${code}${TRESET}\n\n"
    else
        printf "${TRED}Exiting with status ${code}${TRESET}\n\n"
    fi

    exit "${code}"
}

bunt_finish() {
    local code=$?
    local msg="\n"

    [ $code -ne 0 ] && return $code

    if [ $PASS_COUNT -gt 0 ]; then
        msg+="${TGREEN}${TCHECKMARK} ${PASS_COUNT} passed"
    fi

    if [ $PASS_COUNT -gt 0 ] && [ $FAIL_COUNT -gt 0 ]; then
        msg+="${TBLUE} and "
    fi

    if [ $FAIL_COUNT -gt 0 ]; then
        msg+="${TRED}${TXMARK} ${FAIL_COUNT} failed"
    fi

    msg+="${TBLUE} of ${TBLUE}${TOTAL_COUNT} total specs${TRESET}\n\n"

    printf "$msg"

    [ $FAIL_COUNT -gt 0 ] && exit 1 || exit 0
}

setTraps() {
    local trap_func="${1:-bunt_finish}"
    local trap_err_func="${1:-bunt_error}"

    trap - 0 INT TERM
    trap $trap_func 0 INT TERM
    trap - ERR
    trap $trap_err_func ERR
}
setTraps

bunt_describe_reset() {
    unset bunt_xdescribe
}

bunt_it_reset() {
    unset -f given
    unset -f teardown
}

bunt_expect_reset() {
    unset bunt_given_text
    unset bunt_when
    unset bunt_then
    unset bunt_pass
    bunt_expected_call_count=1
    bunt_actual_call_count=0
    PATH="$PATH_BKUP"
}

label() {
    local text="$(echo $1 | tr '[:lower:]' '[:upper:]')"
    echo
    bunt_printRule
    printf "\n  $text"
    bunt_printRule
    echo
}

describe(){
    bunt_describe_reset
    bunt_describe_text=$1" "
}

xdescribe(){
    bunt_describe_text="Skipping ... $1 "
    bunt_xdescribe=true
}

it(){
    bunt_it_reset
    printf "\n  ${TYELLOW}${bunt_describe_text}${1}${TRESET}\n"
}

bunt_set_given() {
    bunt_given_text="$(declare -f given | tail -r | tail -n +2 | tail -r | tail -n +3 | while read line; do echo "   $line"; done)"
}

bunt_given() {
    declare -f given > /dev/null && bunt_set_given && given
}

bunt_teardown() {
    declare -f teardown > /dev/null && teardown
    bunt_expect_reset
}

bunt_printRule() {
    local cols

    cols=$(tput cols)
    (( cols = cols - 4 ))

    printf "\n  "
    eval printf %.0s- '{1..'"$cols"\}
}

bunt_printPass(){
    local msg="$1"

    while (( "$#" )); do shift; done

    printf "${TGREEN}${TCHECKMARK}  "
    [ -n  "$bunt_given_text" ] && printf "given \n${TBLUE}${bunt_given_text}${TRESET}\n       ${TGREEN}"
    printf "%b${TRESET}\n" "$msg"

    (( PASS_COUNT++ ))
}

bunt_printFail(){
    local frame=0
    local msg="$1"

    while (( "$#" )); do shift; done

    printf "${TRED}${TXMARK}  "
    [ -n  "$bunt_given_text" ] && printf "given \n${TBLUE}${bunt_given_text}${TRESET}\n       ${TRED}"
    msg+="\n       Call stack:"
    while $(caller $frame > /dev/null 2>&1); do
        msg+="\n         $(caller $frame)"
        ((frame++));
    done
    printf "%b${TRESET}\n" "$msg"

    (( FAIL_COUNT++ ))
}

bunt_printResult(){
    local msg="$1"

    printf "    "

    if [ "${bunt_pass:-0}" -eq 0 ]; then
        bunt_printFail "$msg"
    else
        bunt_printPass "$msg"
    fi

    (( TOTAL_COUNT++ ))
}

when() {
    local cmd

    if [ "$2 $3" == "is called" ]; then
        cmd=( $1 )
        if [ $# -gt 4 ]; then
            IFS=% cmd+=( ${@:5} )
        fi
        IFS=% bunt_when=( "${cmd[@]}" )
    fi
}

thenn() {
    local cmd
    local isNumber='^[0-9]+$'

    if [ -z "$bunt_xdescribe" ]; then
        bunt_given

        if [ "$1 $2" == "exit with" ]; then
            expectToExitWith $3

        elif [ "$2 $3 $4" == "should be called" ]; then
            cmd=( $1 )
            if [ $# -gt 5 ]; then
                if [ "$5" == "with" ]; then

                    # capture expected arguments
                    bunt_expected_args_tmp=$(mktemp -t tmp)
                    IFS_bkup=$IFS
                    IFS=$'\n'
                    for arg in "${@:6}"; do
                        echo $arg >> "$bunt_expected_args_tmp"
                    done
                    IFS=$IFS_bkup

                    IFS=% cmd+=( ${@:6} )
                elif [[ $5 =~ $isNumber ]] && [ "$6" == "times" ]; then
                    bunt_expected_call_count=$5

                    if [ "$7" == "with" ]; then
                        # capture expected arguments
                        bunt_expected_args_tmp=$(mktemp -t tmp)
                        IFS_bkup=$IFS
                        IFS=$'\n'
                        for arg in "${@:8}"; do
                            echo $arg >> "$bunt_expected_args_tmp"
                        done
                        IFS=$IFS_bkup
                        IFS=% cmd+=( ${@:8} )
                    fi
                fi
            fi
            bunt_then=( "${cmd[@]}" )
            expectToHaveBeenCalled

        elif [ "$1 $2 $3" == "output should match" ]; then
            if [ $# -gt 3 ]; then
                expectOutputToMatch 0 "${@:4}"
            else
                expectOutputToMatch 0
            fi

        elif [ "$1 $2 $3 $4" == "output should not match" ]; then
            if [ $# -gt 4 ]; then
                expectOutputToMatch 1 "${@:5}"
            else
                expectOutputToMatch 1
            fi

        fi

        bunt_teardown
    fi
}

expectToExitWith() {
    local code
    local cmd
    local msg
    local trapped
    local actual

    code="$1"
    trapped=0

    while (( "$#" )); do shift; done

    IFS=% cmd=( "${bunt_when[@]}" )

    if [ ${#cmd[@]} -gt 1 ]; then
        msg="when \`${cmd[0]}\` is called with $(printf "\`%s\` " "${cmd[@]:1}")\n       then it should exit with \`$code\`"
    else
        msg="when \`${cmd[0]}\` is called\n       then it should exit with \`$code\`"
    fi

    exit() {
        actual=$1
    }

    "${cmd[@]}" > /dev/null 2>&1
    actual=${actual:-$?}

    unset -f exit

    if [ -n "$BUNT_DEBUG" ]; then
        echo "expected exit code: $code"
        echo "actual exit code: $actual"
    fi

    if [ "$actual" -eq "$code" ]; then
       bunt_pass=1
    else
       bunt_pass=0
    fi

    bunt_printResult "$msg"
}

expectOutputToMatch() {
    local invert
    local invert_text
    local expected_output
    local cmd
    local msg
    local cmd_output

    invert="$1"
    expected_output="$2"

    while (( "$#" )); do shift; done

    IFS=% cmd=( "${bunt_when[@]}" )

    if [ ${#cmd[@]} -gt 1 ]; then
        msg="when \`${cmd[0]}\` is called with$(printf " \`%s\`" "${cmd[@]:1}")\n       then output should match \`$expected_output\`"
    else
        msg="when \`${cmd[0]}\` is called\n       then output should match \`$expected_output\`"
    fi

    cmd_output=$(${cmd[@]})

    if $(echo "$cmd_output" | grep -q -e "$expected_output"); then
        bunt_pass=1
    else
        bunt_pass=0
    fi

    if [ "$invert" -eq 1 ]; then
        if [ "$bunt_pass" -eq 0 ]; then
            bunt_pass=1
        else
            bunt_pass=0
        fi
        invert_text=" not"
    fi

    if [ "$bunt_pass" -eq 0 ]; then
        if [ $(echo "$cmd_output" | grep -c '$') -gt 1 ]; then
            msg+="\n       expected output to${invert_text} match \`$expected_output\`. actual was:\n\n"
            msg+=$(echo "$cmd_output" | while read line; do echo "         $line"; done)
            msg+="\n"
        else
            msg+="\n       expected output${invert_text} to match \`$expected_output\`. actual was \`$cmd_output\`"
        fi
    fi

    bunt_printResult "$msg"
}

createSpy() {
    local name=$1
    local output=$1
    local code=$1

    while (( "$#" )); do shift; done

    local tmp_dir="$(mktemp -t tmp -d)"
    local tmp_args=$(mktemp -t tmp)
    local tmp_calls=$(mktemp -t tmp)

    echo "call_count=\$(cat \"$tmp_calls\" 2>/dev/null || echo 0)
        (( call_count++ ))
        echo \$call_count >| \"$tmp_calls\"
        IFS_bkup=\$IFS
        IFS=$'\n'
        for arg in \"\$@\"; do
            echo \$arg >> \"${tmp_args}-\${call_count}\"
        done
        IFS=\$IFS_bkup
        [ -n \"$output\" ] && printf \"${output}\" && return \"${code}\"" > "${tmp_dir}/${name}"

    chmod +x "${tmp_dir}/${name}"

    echo $tmp_dir
    echo $tmp_args
    echo $tmp_calls
}

expectToHaveBeenCalled() {
    local subject
    local subject_cmd_name
    local expected_args
    local expected_args_text
    local condition
    local condition_cmd_name
    local subject_output
    local subject_code
    local msg
    local condition_script_name
    local condition_script
    local tmp_files
    local tmp_dir
    local tmp_args
    local tmp_calls

    IFS=% subject=( "${bunt_then[@]}" )
    subject_cmd_name="${subject[0]}"

    IFS=% condition=( "${bunt_when[@]}" )
    condition_cmd_name="${condition[0]}"

    expected_args="${bunt_then[*]:1}"
    if [ -n "${subject[*]:1}" ]; then
        expected_args_text="\`$(cat "$bunt_expected_args_tmp" | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\` \`/g')\`"
    fi

    msg="when \`${condition_cmd_name}\` is called"
    if [ "${#condition[@]}" -gt 1 ]; then
        msg+=" with$(printf " \`%s\`" "${condition[@]:1}")"
    fi
    msg+="\n       then \`${subject_cmd_name}\` should be called"
    if [ "${#subject[@]}" -gt 1 ]; then
        msg+=" with $expected_args_text"
    fi
    msg+=" ${bunt_expected_call_count} times"

    # backup original subject, if function
    if [ "$(type -t "${subject_cmd_name}")" == "function" ]; then
        eval "$(echo "bunt_bkup_${subject_cmd_name}()" && declare -f "${subject_cmd_name}" | tail -n +2)"
        unset -f "${subject_cmd_name}"
    fi

    # replace with spy
    subject_output=$("${subject[@]}" 2>&1)
    subject_code=$?
    IFS=$'\n' tmp_files=( $(createSpy "$subject_cmd_name" "$subject_output" "$subject_code") )
    local tmp_dir="${tmp_files[0]}"
    local tmp_args="${tmp_files[1]}"
    local tmp_calls="${tmp_files[2]}"
    PATH="${tmp_dir}:${PATH}"

    # source condition as script
    condition_script_name="$(mktemp -t tmp)"
    echo "$(declare -f ${condition_cmd_name} | tail -r | tail -n +2 | tail -r | tail -n +3)" > "$condition_script_name"
    IFS=% condition_script=( "source" "$condition_script_name" "${condition[@]:1}" )
    if [ -n "$BUNT_DEBUG" ]; then "${condition_script[@]}"; else "${condition_script[@]}" > /dev/null 2>&1; fi

    # restore original subject, if function
    if [ "$(type -t "bunt_bkup_${subject_cmd_name}")" == "function" ]; then
        eval "$(echo "${subject_cmd_name}()" && declare -f "bunt_bkup_${subject_cmd_name}" | tail -n +2)"
        unset -f "bunt_bkup_${subject_cmd_name}"
    fi

    if [ -n "$BUNT_DEBUG" ]; then echo "subject script: ${tmp_dir}/${subject_cmd_name}"; echo "condition script: ${condition_script[@]}"; fi

    # check call count
    bunt_actual_call_count="$(cat "$tmp_calls")"
    if [ "$bunt_expected_call_count" -eq "$bunt_actual_call_count" ]; then
        bunt_pass=1
    else
        msg+="\n       expected ${bunt_expected_call_count} calls but saw ${bunt_actual_call_count}"
        bunt_pass=0
    fi

    # check arguments
    if [ -n "${subject[*]:1}" ]; then
        for ((i=1;i<=${bunt_actual_call_count};i++)); do
            if [ -n "$BUNT_DEBUG" ]; then echo "actual args: $(cat "${tmp_args}-$i")"; echo "expected args: $(cat "$bunt_expected_args_tmp")"; fi
            if [ -z "$(diff "$bunt_expected_args_tmp" "${tmp_args}-$i")" ]; then
                bunt_pass=1
                break
            else
                bunt_pass=0
            fi
        done
    fi

    # print result
    bunt_printResult "$msg"

}

