#!/usr/bin/env bash

testMe() {
    if [ "$1" == "a b" ] && [ "$2" == "c" ]; then
        echo "$FOO"
        return 0
    else
        echo "error"
        return 1
    fi
}

testMeWrapper() {
    testMe "$2" "$1"
}

outputStuff() {
    if [ -z "$1" ]; then
        echo "success"
    elif [ "$1" == "multiline" ]; then
        printf "foo\nbar\nbam\nqux"
    else
        echo "error"
    fi
}

