#!/usr/bin/env bash

describe "testMe"

    it "should exit 0 when it receives valid arguments"

        when testMe is called with "a b" "c"
        thenn exitWith 0

        when testMe is called with "a b" "c"
        thenn exitWith 0

        when testMe is called with "a" "z"
        thenn exitWith 0 # will fail


    it "should exit 1 when it receives bad arguments"

        when testMe is called with "z" "z"
        thenn exitWith 1

        when testMe is called with "a b" "c"
        thenn exitWith 1 # will fail

        when testMe is called with "a" "b" "c"
        thenn exitWith 1

describe "testMeWrapper"

    it "should pass the arguments but reverse them"

        when testMeWrapper is called with "a b" "c"
        thenn testMe should be called with "c" "a b"

        when testMeWrapper is called with "a b" "c"
        thenn testMe should be called with "a b" "c" # will fail


    it "should have desired output"

        beforeEach() {
            given "FOO=bar"
            FOO="bar"
        }

        afterEach() {
            unset FOO
        }

        when testMe is called with "a b" "c"
        thenn output should match "bar"

        when testMe is called with "a b" "c"
        thenn output should match "foo" # will fail

describe "outputStuff"

    it "should not output errors"

        when outputStuff is called
        thenn output should not match "error"

        when outputStuff is called with "foo"
        thenn output should not match "error" # will fail

        when outputStuff is called with "multiline"
        thenn output should match "foo"

        when outputStuff is called with "multiline"
        thenn output should not match "xyzzy"

        when outputStuff is called with "multiline"
        thenn output should match "xyzzy" # will fail
