#!/usr/bin/env bash


section "passing examples"

feature "testMe"

    scenario "should exit 0 when it receives valid arguments"

        when testMe is called with "a b" "c"
        thenn exit with 0

        when testMe is called with "a b" "c"
        thenn exit with 0

    scenario "should exit 1 when it receives bad arguments"

        when testMe is called with "z" "z"
        thenn exit with 1

        when testMe is called with "a" "b" "c"
        thenn exit with 1

feature "testMeWrapper"

    scenario "should pass the arguments but reverse them"

        when testMeWrapper is called with "a b" "c"
        thenn testMe should be called with "c" "a b"

    scenario "should have desired output"

        given() {
            FOO="bar"
        }

        teardown() {
            unset FOO
        }

        when testMe is called with "a b" "c"
        thenn output should match "bar"

feature "outputStuff"

    scenario "should not output errors"

        when outputStuff is called
        thenn output should not match "error"

        when outputStuff is called with "multiline"
        thenn output should match "foo"

        when outputStuff is called with "multiline"
        thenn output should not match "xyzzy"

feature "retry"

    scenario "should call given function"

        given() {
            foo() {
                return 0
            }
        }

        teardown() {
            unset -f foo
        }

        when retry is called with 1 foo
        thenn foo should be called

    scenario "should call given function n number of times"

        given() {
            foo() {
                return 1
            }
        }

        teardown() {
            unset -f foo
        }

        when retry is called with 3 foo
        thenn foo should be called 3 times

feature "callsSystemCmd"

    scenario "should call curl"

        when callsSystemCmd is called
        thenn curl should be called with --silent -X GET http://localhost/foo

        when callsSystemCmd is called
        thenn curl should be called with -X POST http://localhost/bar

        when callsSystemCmd is called
        thenn curl should be called 2 times


section "failing examples"

feature "testMe"

    scenario "should exit 0 when it receives valid arguments"

        when testMe is called with "a" "z"
        thenn exit with 0 # will fail


    scenario "should exit 1 when it receives bad arguments"

        when testMe is called with "a b" "c"
        thenn exit with 1 # will fail

feature "testMeWrapper"

    scenario "should pass the arguments but reverse them"

        when testMeWrapper is called with "a b" "c"
        thenn testMe should be called with "a b" "c" # will fail


    scenario "should have desired output"

        given() {
            FOO="bar"
        }

        teardown() {
            unset FOO
        }

        when testMe is called with "a b" "c"
        thenn output should match "foo" # will fail

feature "outputStuff"

    scenario "should not output errors"

        when outputStuff is called with "foo"
        thenn output should not match "error" # will fail

        when outputStuff is called with "multiline"
        thenn output should match "xyzzy" # will fail


feature "retry"

    scenario "should call given function n number of times"

        given() {
            foo() {
                return 1
            }
        }

        teardown() {
            unset -f foo
        }

        when retry is called with 3 foo
        thenn foo should be called 4 times
